### ISSUE TITLE
Cannot import library : SyntaxError

### ISSUE THREAD

**Issue by marrakchino** [PyWizards/Selenium_Screenshot#7]
**Describe the bug**
Unable to import package

**To Reproduce**
 ```
[20:27] marrakchino ~$ pip3 install --user Selenium-Screenshot
Collecting Selenium-Screenshot
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from Selenium-Screenshot) (3.1.2)
Requirement already satisfied: selenium in ./.local/lib/python3.5/site-packages (from Selenium-Screenshot) (3.141.0)
Requirement already satisfied: urllib3 in ./.local/lib/python3.5/site-packages (from selenium->Selenium-Screenshot) (1.25.9)
Installing collected packages: Selenium-Screenshot
Successfully installed Selenium-Screenshot-1.7.0
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[20:27] marrakchino ~$ python3
Python 3.5.2 (default, Apr 16 2020, 17:47:17) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from Screenshot import Screenshot_Clipping
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marrakchino/.local/lib/python3.5/site-packages/Screenshot/Screenshot_Clipping.py", line 145
    img_url = os.path.abspath(os.path.join(save_location, f"{uid}.png"))
SyntaxError: invalid syntax
```
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3

**Additional context**

**Comment by sam4u3** [comment]
This package required python version 3.6+

**Comment by marrakchino** [comment]
Thanks. I guess you should update the README.me file then, it says python 3.*.

Regards.

**Comment by sam4u3** [comment]
Sure . Will update it.. hope you like this package... Do support by giving us star on repo. Also you can sponsored this repository
